services:
  app:
    build: .
    container_name: fast-ray-gram
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      APP__HOST: 0.0.0.0
      APP__PORT: 8000
      DB__URL: sqlite+aiosqlite:////app/database/data.db
    volumes:
      - ./database:/app/database
    restart: unless-stopped